# Import Libraries

mengimport package pandas dan numpy, pandas untuk memmbaca data dan membuat dataframe, numpy unutk pengolahan matrix

In [1]:
import pandas as pd
import numpy as np

# Import Data
menggunakan pd.read_excel untuk membaca data excel, parameter sheet_name berguna untuk menentukan sheet yang akan dibaca, index_col berguna untuk menentukan kolom yang akan dijadikan index

In [2]:
df = pd.read_excel("data.xlsx",sheet_name="Sheet2",index_col=0)
df_input = pd.read_excel("data.xlsx",sheet_name="Sheet3")
df_tenaga_kerja = pd.read_excel("data.xlsx",sheet_name="Sheet4")

# Menghitung Matriks A
untuk menghitung matriks A, dapat diperoleh dengan membagi nilai dari tiap kolom dengan nilai dari data df_input

In [3]:
df_A = df.copy()
df_A = df_A.div(df_input.iloc[0], axis=1)
df_A

Pertanian, Kehutanan, \ndan Perikanan  \
Deskripsi                                                                                   
Pertanian, Kehutanan, dan Perikanan                                          6.905771e-02   
Pertambangan dan Penggalian                                                  1.079010e-08   
Industri Pengolahan                                                          1.613619e-02   
Pengadaan Listrik dan Gas                                                    8.112205e-03   
Pengadaan Air, Pengelolaan Sampah, Limbah dan D...                           5.012464e-05   
Konstruksi                                                                   1.710186e-03   
Perdagangan Besar dan Eceran; Reparasi Mobil da...                           2.338319e-02   
Transportasi dan Pergudangan                                                 5.633284e-03   
Penyediaan Akomodasi dan Makan Minum                                         5.100093e-04   
Informasi dan Komunikasi                                                     1.279532e-03   
Jasa Keuangan dan Asuransi                                                   1.725351e-03   
Real Estate                                                                  5.170609e-06   
Jasa Perusahaan                                                              6.273953e-04   
Administrasi Pemerintahan, Pertahanan dan Jamin...                           5.442390e-05   
Jasa Pendidikan                                                              3.668334e-06   
Jasa Kesehatan dan Kegiatan Sosial                                           5.965165e-06   
Jasa Lainnya                                                                 2.406290e-03   

                                                    Pertambangan \ndan Penggalian   \
Deskripsi                                                                            
Pertanian, Kehutanan, dan Perikanan                                       0.000134   
Pertambangan dan Penggalian                                               0.019646   
Industri Pengolahan                                                       0.002501   
Pengadaan Listrik dan Gas                                                 0.002199   
Pengadaan Air, Pengelolaan Sampah, Limbah dan D...                        0.000335   
Konstruksi                                                                0.000030   
Perdagangan Besar dan Eceran; Reparasi Mobil da...                        0.035369   
Transportasi dan Pergudangan                                              0.027960   
Penyediaan Akomodasi dan Makan Minum                                      0.009817   
Informasi dan Komunikasi                                                  0.009426   
Jasa Keuangan dan Asuransi                                                0.000493   
Real Estate                                                               0.012692   
Jasa Perusahaan                                                           0.018291   
Administrasi Pemerintahan, Pertahanan dan Jamin...                        0.000137   
Jasa Pendidikan                                                           0.000009   
Jasa Kesehatan dan Kegiatan Sosial                                        0.000018   
Jasa Lainnya                                                              0.000876   

                                                    Industri \nPengolahan  \
Deskripsi                                                                   
Pertanian, Kehutanan, dan Perikanan                              0.159760   
Pertambangan dan Penggalian                                      0.014431   
Industri Pengolahan                                              0.051440   
Pengadaan Listrik dan Gas                                        0.009334   
Pengadaan Air, Pengelolaan Sampah, Limbah dan D...               0.000091   
Konstruksi                                                       0.001439   
Perdagangan Besar dan Eceran; Rep

untuk mengubah menjadi matriks, kita dapat menggunakan method .values

In [6]:
matrix_A = df_A.values
#set matrix view so it's not truncated
np.set_printoptions(threshold=np.inf)

#set decimal precision
np.set_printoptions(precision=3)

print(matrix_A)

[[6.906e-02 1.343e-04 1.598e-01 2.105e-05 4.756e-04 4.388e-03 1.160e-06
  0.000e+00 7.209e-02 5.326e-08 4.958e-05 0.000e+00 0.000e+00 2.481e-03
  4.926e-04 1.986e-02 6.368e-03]
 [1.079e-08 1.965e-02 1.443e-02 2.231e-04 5.890e-08 4.613e-02 4.195e-08
  8.019e-08 1.945e-04 8.073e-11 4.963e-10 3.083e-08 2.174e-08 6.276e-04
  6.367e-08 1.026e-07 3.068e-08]
 [1.614e-02 2.501e-03 5.144e-02 9.037e-04 1.816e-03 7.785e-02 5.023e-03
  6.805e-03 3.838e-02 4.233e-03 4.154e-03 1.598e-03 5.058e-03 1.287e-02
  1.022e-02 1.617e-02 1.695e-02]
 [8.112e-03 2.199e-03 9.334e-03 5.700e-01 4.463e-02 1.412e-03 5.277e-03
  4.940e-03 1.259e-02 1.393e-02 1.750e-03 3.532e-03 7.713e-03 1.044e-02
  8.329e-03 1.477e-02 2.027e-02]
 [5.012e-05 3.349e-04 9.093e-05 1.428e-04 3.221e-02 3.181e-05 3.544e-05
  1.680e-04 2.192e-03 3.195e-05 5.029e-05 1.730e-05 2.189e-05 6.094e-04
  2.067e-04 5.694e-04 1.952e-03]
 [1.710e-03 2.960e-05 1.439e-03 6.292e-05 4.603e-03 1.866e-02 1.138e-04
  9.949e-04 7.416e-04 8.197e-04 9.192e-03 7

# Membuat Matriks Identitas
untuk membuat matriks identitas, kita dapat menggunakan method np.identity(n) dengan n adalah ukuran matriks identitas yang akan dibuat

In [7]:
# buat matriks identitas 17x17
matrix_I = np.identity(17)
print(matrix_I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# menghitung matriks (I-A)
perhitungan ini dapat dilakukan dengan cara mengurangkan matriks I dengan matriks A

In [8]:
matrix_I_A = matrix_I - matrix_A
print(matrix_I_A)

[[ 9.309e-01 -1.343e-04 -1.598e-01 -2.105e-05 -4.756e-04 -4.388e-03
  -1.160e-06  0.000e+00 -7.209e-02 -5.326e-08 -4.958e-05  0.000e+00
   0.000e+00 -2.481e-03 -4.926e-04 -1.986e-02 -6.368e-03]
 [-1.079e-08  9.804e-01 -1.443e-02 -2.231e-04 -5.890e-08 -4.613e-02
  -4.195e-08 -8.019e-08 -1.945e-04 -8.073e-11 -4.963e-10 -3.083e-08
  -2.174e-08 -6.276e-04 -6.367e-08 -1.026e-07 -3.068e-08]
 [-1.614e-02 -2.501e-03  9.486e-01 -9.037e-04 -1.816e-03 -7.785e-02
  -5.023e-03 -6.805e-03 -3.838e-02 -4.233e-03 -4.154e-03 -1.598e-03
  -5.058e-03 -1.287e-02 -1.022e-02 -1.617e-02 -1.695e-02]
 [-8.112e-03 -2.199e-03 -9.334e-03  4.300e-01 -4.463e-02 -1.412e-03
  -5.277e-03 -4.940e-03 -1.259e-02 -1.393e-02 -1.750e-03 -3.532e-03
  -7.713e-03 -1.044e-02 -8.329e-03 -1.477e-02 -2.027e-02]
 [-5.012e-05 -3.349e-04 -9.093e-05 -1.428e-04  9.678e-01 -3.181e-05
  -3.544e-05 -1.680e-04 -2.192e-03 -3.195e-05 -5.029e-05 -1.730e-05
  -2.189e-05 -6.094e-04 -2.067e-04 -5.694e-04 -1.952e-03]
 [-1.710e-03 -2.960e-05 -1.439

# menghitung inverse matriks (I-A)
untuk menghitung inverse matriks, kita menggunakan fungsi np.linalg.inv(m) dengan m adalah matriks yang akan dihitung

In [95]:
matrix_I_A_inv = np.linalg.inv(matrix_I_A)
matrix_I_A_inv

array([[1.07762420e+00, 2.05551897e-03, 1.82593558e-01, 2.21901902e-03,
        3.06150582e-03, 2.17436982e-02, 2.87174308e-03, 7.46535281e-03,
        8.59202997e-02, 2.89099344e-03, 1.84647473e-03, 2.85804431e-03,
        9.42856529e-03, 1.73037268e-02, 9.05776314e-03, 2.88263975e-02,
        1.54769374e-02],
       [3.85217959e-04, 1.02017800e+00, 1.57620108e-02, 6.72040587e-04,
        4.10761811e-04, 4.93127825e-02, 3.62879060e-04, 3.50758904e-04,
        9.87277345e-04, 2.82976836e-04, 6.03929962e-04, 4.01769539e-03,
        3.21194253e-04, 1.41118759e-03, 5.39236392e-04, 4.70768363e-04,
        7.42574612e-04],
       [1.89352124e-02, 4.22699521e-03, 1.05901194e+00, 4.39989048e-03,
        4.58520215e-03, 8.64760511e-02, 7.69550057e-03, 1.22258190e-02,
        4.35140005e-02, 7.86396488e-03, 6.48504577e-03, 9.81580197e-03,
        1.16211475e-02, 2.16860389e-02, 1.53731020e-02, 2.07562293e-02,
        2.26060777e-02],
       [2.16067598e-02, 7.97354083e-03, 2.91045790e-02, 2.329

# analisis keterkaitan ke belakang (tiap variabel)
perhitungan ini dapat dilakukan dengan menjumlahkan tiap baris dari matriks inverse (I-A). perhitungan dapat dilakukan dengan menggunakan method .sum(axis=0)

In [98]:
matrix_I_A_inv.sum(axis=0)

array([1.17577724, 1.19166375, 1.46322791, 2.60432609, 1.34206906,
       1.41718514, 1.29738391, 1.41882544, 1.33011775, 1.48108587,
       1.20238581, 1.29889504, 1.48215251, 1.44553691, 1.27555029,
       1.29286159, 1.39084076])

untuk mempermudah pembacaan, dapat diubah menjadi bentuk dataframe dengan kolom yang sesuai

In [99]:
df_belakang = pd.DataFrame(matrix_I_A_inv.sum(axis=0).reshape(1,17),columns=df.columns)
df_belakang

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                               1.175777                        1.191664   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0               1.463228                      2.604326   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                           1.342069               1.417185   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                           1.297384                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         1.418825                                1.330118   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    1.481086                      1.202386     1.298895   

   Jasa \nPerusahaan  \
0           1.482153   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                           1.445537                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0           1.275550                              1.292862        1.390841

menghitung rata-rata dari df_belakang

In [100]:
#rata-rata 
df_belakang.mean(axis=1) # agar dirata-ratakan semua kolom, maka menggunakan axis = 1

0   1.418229
dtype: float64

# analisis keterkaitan ke depan (tiap baris)
perhitungan ini dapat dilakukan dengan menjumlahkan tiap kolom dari matriks inverse (I-A). perhitungan dapat dilakukan dengan menggunakan method .sum(axis=1)

In [101]:
matrix_I_A_inv.sum(axis=1)

array([1.4732438 , 1.09681129, 1.35727802, 2.82016436, 1.04235412,
       1.17214079, 1.52755764, 1.63837237, 1.6391137 , 1.7097599 ,
       1.57728906, 1.27356273, 1.53242451, 1.04390249, 1.04454348,
       1.01660528, 1.14476156])

untuk mempermudah pembacaan, dapat diubah menjadi bentuk dataframe dengan kolom yang sesuai

In [102]:
#analisis keterkaitan ke depan (tiap baris)
df_depan = pd.DataFrame(matrix_I_A_inv.sum(axis=1).reshape(17,1),index=df.index,columns=["keterkaitan ke depan"])
df_depan


keterkaitan ke depan
Deskripsi                                                               
Pertanian, Kehutanan, dan Perikanan                             1.473244
Pertambangan dan Penggalian                                     1.096811
Industri Pengolahan                                             1.357278
Pengadaan Listrik dan Gas                                       2.820164
Pengadaan Air, Pengelolaan Sampah, Limbah dan D...              1.042354
Konstruksi                                                      1.172141
Perdagangan Besar dan Eceran; Reparasi Mobil da...              1.527558
Transportasi dan Pergudangan                                    1.638372
Penyediaan Akomodasi dan Makan Minum                            1.639114
Informasi dan Komunikasi                                        1.709760
Jasa Keuangan dan Asuransi                                      1.577289
Real Estate                                                     1.273563
Jasa Perusahaan                                                 1.532425
Administrasi Pemerintahan, Pertahanan dan Jamin...              1.043902
Jasa Pendidikan                                                 1.044543
Jasa Kesehatan dan Kegiatan Sosial                              1.016605
Jasa Lainnya                                                    1.144762

# Menghitung IDP
perhitungan IDP dapat dilakukan dengan membagi nilai dari df_belakang dengan rata-rata dari df_belakang

perhitungan rata-rata dari df_belakng dapat dilakukan dengan .mean(axis = 1), axis 1 diguanakn karena ingin dihitung rata-rata dari semua kolom

In [105]:
df_belakang.mean(axis=1)

0   1.418229
dtype: float64

untuk membagi keseluruhan nilai dengan nilai rata-rata dapat dilakukan dengan .div(a) dengan a adalah pembagi

In [108]:
df_belakang.div(df_belakang.mean(axis=1),axis = 0) #axis = 0 agar dirata-ratakan semua baris

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                               0.829046                        0.840248   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0               1.031729                      1.836323   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                           0.946300               0.999264   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                           0.914792                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         1.000421                                0.937873   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    1.044321                      0.847808     0.915857   

   Jasa \nPerusahaan  \
0           1.045073   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                           1.019255                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0           0.899397                              0.911603        0.980689

# Menghitung IDK
perhitungan IDK dapat dilakukan dengan membagi nilai dari df_depan dengan rata-rata dari df_depan

rata-rata df_depan dapat dihitung dengan cara .mean()

In [110]:
df_depan.mean(axis = 0)

keterkaitan ke depan   1.418229
dtype: float64

untuk membagi keseluruhan nilai dengan nilai rata-rata dapat dilakukan dengan .div(a) dengan a adalah pembagi

In [112]:
#hitung IDK 
df_depan.div(df_depan.mean(axis = 0),axis = 1)

keterkaitan ke depan
Deskripsi                                                               
Pertanian, Kehutanan, dan Perikanan                             1.038792
Pertambangan dan Penggalian                                     0.773367
Industri Pengolahan                                             0.957023
Pengadaan Listrik dan Gas                                       1.988512
Pengadaan Air, Pengelolaan Sampah, Limbah dan D...              0.734969
Konstruksi                                                      0.826482
Perdagangan Besar dan Eceran; Reparasi Mobil da...              1.077088
Transportasi dan Pergudangan                                    1.155225
Penyediaan Akomodasi dan Makan Minum                            1.155747
Informasi dan Komunikasi                                        1.205560
Jasa Keuangan dan Asuransi                                      1.112154
Real Estate                                                     0.897995
Jasa Perusahaan                                                 1.080520
Administrasi Pemerintahan, Pertahanan dan Jamin...              0.736061
Jasa Pendidikan                                                 0.736513
Jasa Kesehatan dan Kegiatan Sosial                              0.716813
Jasa Lainnya                                                    0.807177

# Koefisien Tenaga Kerja

koefisien tenaga kerja dapat dihitung dengan membagi df_tenaga_kerja dengan df_input

In [115]:
koef_tk = df_tenaga_kerja.div(df_input.iloc[0],axis = 1) #iloc[0] menunjukkan baris pertama dari df_input
koef_tk

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                               0.020056                        0.002042   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0               0.012810                      0.000610   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                           0.021068               0.004193   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                           0.019683                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         0.002264                                0.004838   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    0.000774                      0.004344     0.000319   

   Jasa \nPerusahaan  \
0           0.005473   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                           0.009874                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0           0.009396                              0.006705        0.010121

# Angka Pengganda Tenaga Kerja
dapat dihitung melalui perkalian matriks koef_tk dengan inverse matrix(I-A)

membuat matriks koef_tk dapat dilakukan dengan .values

In [116]:
matriks_tk = koef_tk.values
matriks_tk

array([[0.02005645, 0.00204221, 0.01280958, 0.00061046, 0.02106805,
        0.00419304, 0.01968315, 0.0022638 , 0.00483809, 0.00077356,
        0.00434395, 0.00031865, 0.00547315, 0.00987384, 0.00939618,
        0.00670544, 0.01012117]])

perkalian matriks dapat dilakukan dengan fungsi dot

In [120]:
np.dot(matriks_tk,matrix_I_A_inv)

array([[0.02252487, 0.00332485, 0.01890742, 0.00314082, 0.02322426,
        0.00790656, 0.02092896, 0.00472525, 0.00842395, 0.00227653,
        0.00533693, 0.00176762, 0.00752866, 0.01241613, 0.01103691,
        0.0091478 , 0.0123521 ]])

agar lebih rapi, dapat diubah menjadi dataframe

In [122]:
pengganda_tk = pd.DataFrame(np.dot(matriks_tk,matrix_I_A_inv),columns=df_tenaga_kerja.columns)
pengganda_tk

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                               0.022525                        0.003325   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0               0.018907                      0.003141   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                           0.023224               0.007907   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                           0.020929                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         0.004725                                0.008424   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    0.002277                      0.005337     0.001768   

   Jasa \nPerusahaan  \
0           0.007529   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                           0.012416                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0           0.011037                              0.009148        0.012352

hitung pengganda 100 dan 1000

In [133]:
pengganda_tk.multiply(100)

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                               2.252487                        0.332485   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0               1.890742                      0.314082   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                           2.322426               0.790656   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                           2.092896                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         0.472525                                0.842395   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    0.227653                      0.533693     0.176762   

   Jasa \nPerusahaan  \
0           0.752866   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                           1.241613                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0           1.103691                              0.914780        1.235210

In [135]:
pengganda_tk.multiply(1000)

Pertanian, Kehutanan, \ndan Perikanan  Pertambangan \ndan Penggalian   \
0                              22.524869                        3.324846   

   Industri \nPengolahan  Pengadaan, \nListrik dan Gas  \
0              18.907425                      3.140819   

   Pengadaan Air, \nPengelolaan Sampah, \nLimbah dan Daur Ulang  Konstruksi  \
0                                          23.224262               7.906556   

   Perdagangan Besar \ndan Eceran; \nReparasi Mobil \ndan Sepeda Motor  \
0                                          20.928960                     

   Transportasi \ndan Pergudangan   Penyediaan Akomodasi \ndan Makan Minum  \
0                         4.725249                                8.423951   

   Informasi dan \nKomunikasi  Jasa Keuangan \ndan Asuransi  Real Estate  \
0                    2.276530                      5.336930     1.767622   

   Jasa \nPerusahaan  \
0           7.528664   

   Administrasi Pemerintahan, \nPertahanan dan Jaminan \nSosial Wajib  \
0                                          12.416131                    

   Jasa \nPendidikan  Jasa Kesehatan \ndan Kegiatan Sosial  Jasa \nLainnya  
0          11.036913                              9.147805       12.352096